[package]
name = "day13"
version = "0.1.0"
edition = "2021"
default-run = "part2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
eyre = "0.6.8"
joinery = "3.1.0"
nom = "7.1.1"

[features]
